package httpserver

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/modelcontextprotocol/go-sdk/auth"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/zetic-ai/melange-cli/internal/api"
)

// fakeClock is an injectable, advanceable clock for TTL and refill tests.
type fakeClock struct {
	mu sync.Mutex
	t  time.Time
}

// The base time sits firmly in the past so a limiter clock frozen mid-test
// can never leap ahead of buckets created under the real clock (a positive
// jump would refill them and mask the 429 path).
func newFakeClock() *fakeClock {
	return &fakeClock{t: time.Date(2020, 1, 2, 3, 4, 5, 0, time.UTC)}
}

func (c *fakeClock) Now() time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.t
}

func (c *fakeClock) Advance(d time.Duration) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.t = c.t.Add(d)
}

// countingMeStub is newMeStub plus an atomic count of /v1/me hits, the oracle
// for the MeVerifier cache tests.
type countingMeStub struct {
	*httptest.Server
	calls atomic.Int64
}

func newCountingMeStub(t *testing.T, users map[string]string) *countingMeStub {
	t.Helper()
	s := &countingMeStub{}
	s.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/v1/me" {
			http.NotFound(w, r)
			return
		}
		s.calls.Add(1)
		token, ok := strings.CutPrefix(r.Header.Get("Authorization"), "Bearer ")
		if name, known := users[token]; ok && known {
			w.Header().Set("Content-Type", "application/json")
			_, _ = io.WriteString(w, meBody(name))
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		_, _ = io.WriteString(w, `{"type":"error","error":{"type":"authentication_error","message":"unknown token"}}`)
	}))
	t.Cleanup(s.Close)
	return s
}

// testAPIOptions mirrors (*Server).apiOptions for direct MeVerifier tests:
// Debug always nil, host fixed, token per bearer.
func testAPIOptions(host string) func(string) api.Options {
	return func(bearer string) api.Options {
		return api.Options{
			Host:      host,
			Token:     bearer,
			UserAgent: "melange-cli-test/0.0.0",
			Timeout:   5 * time.Second,
		}
	}
}

// newTestMeVerifier builds a MeVerifier against host with an injected clock,
// a discarding logger, and no resource identity (audience enforcement off).
func newTestMeVerifier(host string, clk *fakeClock) *MeVerifier {
	return newTestMeVerifierLogging(host, clk, nil)
}

// newTestMeVerifierLogging is newTestMeVerifier with the failure detail routed
// to a caller-supplied logger, so a test can assert what was withheld from the
// response body actually reached the operator.
func newTestMeVerifierLogging(host string, clk *fakeClock, logger *slog.Logger) *MeVerifier {
	return newTestMeVerifierResource(host, "", clk, logger)
}

// newTestMeVerifierResource is the full-control constructor: resource is the
// canonical resource URL the verifier enforces audiences against ("" = off).
func newTestMeVerifierResource(host, resource string, clk *fakeClock, logger *slog.Logger) *MeVerifier {
	v := NewMeVerifier(testAPIOptions(host), resource, logger)
	// Safe before the verifier is shared: now is written only here, during
	// setup, and read under mu once requests start.
	v.now = clk.Now
	return v
}

// deadHost starts and immediately closes an httptest server, yielding a URL
// whose host is reachable only as a connection refusal — the transport-failure
// fixture.
func deadHost(t *testing.T) string {
	t.Helper()
	s := httptest.NewServer(http.HandlerFunc(http.NotFound))
	s.Close()
	return s.URL
}

// dialFailureMarker returns the substring Go itself embeds in every failed
// dial error for addr — `dial tcp host:port:` — which is generated by the net
// package and therefore identical on every OS and locale. Transport-failure
// assertions must anchor on this marker, never on OS error text: the
// refused-connection suffix is "connect: connection refused" on Unix but
// "connectex: No connection could be made because the target machine actively
// refused it." on Windows, and Windows system error strings are localized.
// TestDialFailureMarkerMatchesRealOSErrors pins this against both literals.
func dialFailureMarker(addr string) string {
	return "dial tcp " + addr + ":"
}

// TestDialFailureMarkerMatchesRealOSErrors pins dialFailureMarker against the
// literal refused-dial error text each OS actually produces (the Windows line
// is verbatim from a windows-latest CI run), so the marker's OS-agnosticism is
// proven by test rather than by reasoning. It must match every OS's dial error
// and must NOT match text that merely mentions the address without a dial
// failure — otherwise the negative body assertions would be vacuous.
func TestDialFailureMarkerMatchesRealOSErrors(t *testing.T) {
	const addr = "127.0.0.1:50025"
	cases := []struct {
		name string
		text string
		want bool
	}{
		{
			"unix refused dial",
			`Get "http://127.0.0.1:50025/v1/me": dial tcp 127.0.0.1:50025: connect: connection refused`,
			true,
		},
		{
			"windows refused dial (CI literal)",
			`Get "http://127.0.0.1:50025": dial tcp 127.0.0.1:50025: connectex: No connection could be made because the target machine actively refused it.`,
			true,
		},
		{
			"windows localized suffix still matches",
			`Get "http://127.0.0.1:50025": dial tcp 127.0.0.1:50025: connectex: Es konnte keine Verbindung hergestellt werden.`,
			true,
		},
		{
			"static sentinel does not match",
			"token validation unavailable",
			false,
		},
		{
			"address alone without a dial failure does not match",
			`upstream 127.0.0.1:50025 returned status 404`,
			false,
		},
		{
			"dial failure for a different address does not match",
			`dial tcp 127.0.0.1:9999: connect: connection refused`,
			false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, strings.Contains(tc.text, dialFailureMarker(addr)))
		})
	}
}

func TestPassthroughVerifier(t *testing.T) {
	ctx := context.Background()
	// Any non-empty token passes, whatever its shape: ztp_ personal tokens,
	// zoa_ OAuth tokens (CLI-PR4 — this case is the regression pin), or
	// formats not invented yet. The relay must not gatekeep token formats.
	for _, token := range []string{
		"ztp_0123456789abcdef",
		"zoa_0123456789abcdef",
		"opaque-token-with-no-prefix",
	} {
		info, err := PassthroughVerifier(ctx, token, nil)
		require.NoError(t, err, "token %q must pass", token)
		require.NotNil(t, info)
	}

	_, err := PassthroughVerifier(ctx, "", nil)
	require.Error(t, err)
	assert.ErrorIs(t, err, auth.ErrInvalidToken, "empty bearer must be the SDK's 401, not a 500")
}

// TestZoaShapedTokenFlowsEndToEnd pins the no-prefix-gatekeeping contract
// through the whole stack: a zoa_-shaped OAuth token must reach the API and
// run tools, so CLI-PR4 cannot regress into a ztp_-only check.
func TestZoaShapedTokenFlowsEndToEnd(t *testing.T) {
	const zoa = "zoa_e2e_0123456789abcdef"
	stub := newMeStub(t, map[string]string{zoa: "ana"})
	_, ts := newTestServer(t, stub.URL, nil)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	session := connectSession(t, ctx, ts.URL, zoa)
	text, isErr, err := callWhoami(ctx, session)
	require.NoError(t, err)
	assert.False(t, isErr, "zoa_-shaped token must run tools: %s", text)
	assert.Contains(t, text, "ana@example.com")
}

// TestUnauthenticated401Shape pins the 401 contract at the middleware seam:
// missing/empty/non-bearer credentials are rejected by the SDK middleware
// with a WWW-Authenticate Bearer challenge, and the protected handler is
// never invoked.
func TestUnauthenticated401Shape(t *testing.T) {
	handlerInvoked := false
	sentinel := http.HandlerFunc(func(http.ResponseWriter, *http.Request) { handlerInvoked = true })
	chain := AuthMiddleware(PassthroughVerifier, "", sentinel)

	cases := []struct {
		name          string
		authorization string
	}{
		{"missing header", ""},
		{"empty bearer", "Bearer "},
		{"wrong scheme", "Basic dXNlcjpwYXNz"},
		{"bare token no scheme", "ztp_0123456789abcdef"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			handlerInvoked = false
			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(initializeBody))
			if tc.authorization != "" {
				req.Header.Set("Authorization", tc.authorization)
			}
			rec := httptest.NewRecorder()
			chain.ServeHTTP(rec, req)

			assert.Equal(t, http.StatusUnauthorized, rec.Code)
			assert.Equal(t, "Bearer", rec.Header().Get("WWW-Authenticate"),
				"401 must carry the RFC 9110 Bearer challenge")
			assert.False(t, handlerInvoked, "MCP handler must never run without credentials")
		})
	}
}

// TestUnauthenticated401ThroughStack verifies the same 401 shape over a real
// server (mux, origin middleware, streamable handler all in place).
func TestUnauthenticated401ThroughStack(t *testing.T) {
	_, ts := newTestServer(t, "https://api.invalid", nil)

	resp := postMCP(t, ts.URL, "", "", strings.NewReader(initializeBody))
	assert.Equal(t, http.StatusUnauthorized, resp.StatusCode)
	assert.Equal(t, "Bearer", resp.Header.Get("WWW-Authenticate"))
}

func TestMeVerifierValidTokenRunsTools(t *testing.T) {
	stub := newMeStub(t, map[string]string{"token-alice": "alice"})
	_, ts := newTestServer(t, stub.URL, func(c *Config) { c.ValidateTokens = true })

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	session := connectSession(t, ctx, ts.URL, "token-alice")
	text, isErr, err := callWhoami(ctx, session)
	require.NoError(t, err)
	assert.False(t, isErr, "validated token must run tools: %s", text)
	assert.Contains(t, text, "alice@example.com")
}

// TestMeVerifierRejects401WithChallenge: with --validate-tokens an unknown
// bearer dies at the door — SDK 401 with the Bearer challenge — and the
// response never echoes the token.
func TestMeVerifierRejects401WithChallenge(t *testing.T) {
	const bad = "token-unknown-31415926"
	stub := newCountingMeStub(t, map[string]string{"token-alice": "alice"})
	_, ts := newTestServer(t, stub.URL, func(c *Config) { c.ValidateTokens = true })

	resp := postMCP(t, ts.URL, bad, "", strings.NewReader(initializeBody))
	assert.Equal(t, http.StatusUnauthorized, resp.StatusCode)
	assert.Equal(t, "Bearer", resp.Header.Get("WWW-Authenticate"))
	body, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	assert.NotContains(t, string(body), bad, "the bearer must never appear in the 401 body")
	assert.Equal(t, int64(1), stub.calls.Load(), "rejection happens at the door, before any tool path")
}

func TestMeVerifierMapsScopesAndExpiration(t *testing.T) {
	ctx := context.Background()

	t.Run("scopes, no expiry", func(t *testing.T) {
		stub := newCountingMeStub(t, map[string]string{"token-alice": "alice"})
		v := newTestMeVerifier(stub.URL, newFakeClock())
		info, err := v.Verify(ctx, "token-alice", nil)
		require.NoError(t, err)
		assert.Equal(t, []string{"read"}, info.Scopes, "scopes must map from the /v1/me token block")
		assert.True(t, info.Expiration.IsZero(), "absent expires_at maps to zero (AllowMissingExpiration)")
		assert.Equal(t, "alice@example.com", info.UserID,
			"the account identity must ride into TokenInfo.UserID (never the token)")
	})

	t.Run("expires_at maps to Expiration", func(t *testing.T) {
		expires := time.Date(2027, 1, 2, 3, 4, 5, 0, time.UTC)
		stub := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintf(w, `{"user":{"email":"e@example.com","nickname":"e"},`+
				`"account":{"name":"e","type":"personal"},`+
				`"token":{"name":"e-token","scopes":["read","write"],"expires_at":%q}}`,
				expires.Format(time.RFC3339))
		}))
		t.Cleanup(stub.Close)
		v := newTestMeVerifier(stub.URL, newFakeClock())
		info, err := v.Verify(ctx, "token-e", nil)
		require.NoError(t, err)
		assert.Equal(t, []string{"read", "write"}, info.Scopes)
		assert.True(t, expires.Equal(info.Expiration),
			"expires_at must ride into TokenInfo so the SDK enforces it per request")
	})
}

// meOAuthBody renders the enriched /v1/me response an OAuth (zoa_) bearer
// gets: the PAT shape plus token.aud — a JSON string, or null when the grant
// named no resource — exactly the backend's MeOAuthResponse
// (zetic/public/me.py). PAT responses never carry the aud key at all.
func meOAuthBody(name string, aud *string) string {
	audJSON := "null"
	if aud != nil {
		audJSON = fmt.Sprintf("%q", *aud)
	}
	return fmt.Sprintf(`{"user":{"email":"%[1]s@example.com","nickname":"%[1]s"},`+
		`"account":{"name":"%[1]s","type":"personal"},`+
		`"token":{"name":"%[1]s-client","scopes":["read","write"],"aud":%[2]s}}`, name, audJSON)
}

func strPtr(s string) *string { return &s }

// staticBodyStub serves the given body for every /v1/me hit, counting calls.
func staticBodyStub(t *testing.T, body string) *countingMeStub {
	t.Helper()
	s := &countingMeStub{}
	s.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		s.calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, body)
	}))
	t.Cleanup(s.Close)
	return s
}

// TestMeVerifierOAuthAudience pins the audience half of the resource-server
// contract: /v1 deliberately does not enforce aud (the backend documents this
// as the MCP server's job), so the verifier must reject an OAuth token bound
// to a different resource, while accepting every unbound credential — PATs
// (no aud key) and OAuth grants that named no resource (aud null).
func TestMeVerifierOAuthAudience(t *testing.T) {
	ctx := context.Background()
	const canonical = "https://mcp.zetic.ai"

	accepted := []struct {
		name string
		body string
	}{
		{"matching aud", meOAuthBody("oana", strPtr(canonical))},
		{"matching aud with trailing slash", meOAuthBody("oana", strPtr(canonical+"/"))},
		{"null aud: grant named no resource, not audience-bound", meOAuthBody("oana", nil)},
		{"absent aud: a PAT is not audience-bound", meBody("oana")},
	}
	for _, tc := range accepted {
		t.Run("accepts "+tc.name, func(t *testing.T) {
			stub := staticBodyStub(t, tc.body)
			v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(), nil)
			info, err := v.Verify(ctx, "token-oana", nil)
			require.NoError(t, err)
			assert.NotEmpty(t, info.Scopes, "scopes must be populated alongside audience acceptance")
			assert.Equal(t, "oana@example.com", info.UserID)
		})
	}

	t.Run("rejects a mismatched aud with a static 401", func(t *testing.T) {
		const bearer = "token-wrong-resource-2645751311"
		stub := staticBodyStub(t, meOAuthBody("mallory", strPtr("https://evil.example")))
		logs := &syncBuffer{}
		v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(),
			slog.New(slog.NewTextHandler(logs, &slog.HandlerOptions{Level: slog.LevelDebug})))

		_, err := v.Verify(ctx, bearer, nil)
		require.Error(t, err)
		assert.ErrorIs(t, err, auth.ErrInvalidToken, "a mismatched audience is a 401, not a 500")
		// The SDK copies err.Error() into the 401 body, so the message must
		// stay static: no aud, no configured resource, no token bytes.
		assert.NotContains(t, err.Error(), "evil.example")
		assert.NotContains(t, err.Error(), canonical)
		assert.NotContains(t, err.Error(), bearer)

		// The withheld detail reaches the operator log — without the bearer.
		captured := logs.String()
		assert.Contains(t, captured, "evil.example", "the mismatched aud must reach the server log")
		assert.Contains(t, captured, canonical, "the expected resource must reach the server log")
		assert.NotContains(t, captured, bearer, "the bearer must never reach the server log")
	})

	t.Run("mismatches are never cached", func(t *testing.T) {
		stub := staticBodyStub(t, meOAuthBody("mallory", strPtr("https://evil.example")))
		v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(), nil)
		for i := int64(1); i <= 3; i++ {
			_, err := v.Verify(ctx, "token-wrong", nil)
			require.ErrorIs(t, err, auth.ErrInvalidToken)
			assert.Equal(t, i, stub.calls.Load(),
				"a rejected audience is a negative result and must not be cached")
		}
	})

	t.Run("matching aud is cached like any positive", func(t *testing.T) {
		stub := staticBodyStub(t, meOAuthBody("oana", strPtr(canonical)))
		v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(), nil)
		for i := 0; i < 3; i++ {
			info, err := v.Verify(ctx, "token-oana", nil)
			require.NoError(t, err)
			assert.Equal(t, []string{"read", "write"}, info.Scopes,
				"cache hits must carry the OAuth scopes")
		}
		assert.Equal(t, int64(1), stub.calls.Load(),
			"an audience-checked positive is served from cache inside the TTL")
	})

	t.Run("canary: zoa_ bearer without an aud key fails closed", func(t *testing.T) {
		// The backend contract puts an aud key (string or null) on EVERY
		// zoa_ bearer's /v1/me response — its absence is the PAT-shape
		// discriminator. If the field is ever renamed or moved, treating the
		// OAuth response as "unbound" would silently turn audience
		// enforcement off for every OAuth token; the verifier must fail
		// closed (a retryable 500, not a 401 that burns the credential).
		const bearer = "zoa_contract_drift_1259921049"
		stub := staticBodyStub(t, meBody("drifted"))
		logs := &syncBuffer{}
		v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(),
			slog.New(slog.NewTextHandler(logs, &slog.HandlerOptions{Level: slog.LevelDebug})))

		_, err := v.Verify(ctx, bearer, nil)
		require.Error(t, err)
		assert.ErrorIs(t, err, errValidationUnavailable,
			"a missing aud on an OAuth bearer is contract drift, not a verdict on the token")
		assert.NotErrorIs(t, err, auth.ErrInvalidToken)
		assert.NotContains(t, err.Error(), bearer)
		assert.Contains(t, logs.String(), "aud", "the drift detail must reach the operator log")
		assert.NotContains(t, logs.String(), bearer, "the bearer must never reach the server log")
	})

	t.Run("canary fires even without a configured resource", func(t *testing.T) {
		// The canary is about the response shape, not this server's config:
		// a zoa_ bearer answered with the PAT shape is drift wherever it
		// happens (zoa_ acceptance and the aud enrichment shipped together,
		// so no real backend produces this).
		stub := staticBodyStub(t, meBody("drifted"))
		v := newTestMeVerifier(stub.URL, newFakeClock())
		_, err := v.Verify(ctx, "zoa_contract_drift_no_resource", nil)
		assert.ErrorIs(t, err, errValidationUnavailable)
	})

	t.Run("ztp_ bearer without an aud key stays accepted", func(t *testing.T) {
		// The canary is zoa_-scoped: a PAT's response never carries the key,
		// and PATs must keep working on the HTTP transport.
		stub := staticBodyStub(t, meBody("patty"))
		v := newTestMeVerifierResource(stub.URL, canonical, newFakeClock(), nil)
		info, err := v.Verify(ctx, "ztp_plain_pat_1442249570", nil)
		require.NoError(t, err)
		assert.Equal(t, "patty@example.com", info.UserID)
	})

	t.Run("no configured resource skips enforcement", func(t *testing.T) {
		// Without a resource identity the server has nothing to compare aud
		// against; enforcement requires --resource. Plain --validate-tokens
		// keeps the PR2 posture: validity yes, audience no.
		stub := staticBodyStub(t, meOAuthBody("oana", strPtr("https://elsewhere.example")))
		v := newTestMeVerifier(stub.URL, newFakeClock())
		info, err := v.Verify(ctx, "token-oana", nil)
		require.NoError(t, err)
		assert.Equal(t, []string{"read", "write"}, info.Scopes)
	})
}

// TestMeVerifierRefreshTokenRejected pins our side of the backend's refusal
// of zor_ refresh tokens on /v1: the 401 maps to auth.ErrInvalidToken (the
// SDK's 401) with no token bytes anywhere, and — like every negative — is
// never cached.
func TestMeVerifierRefreshTokenRejected(t *testing.T) {
	ctx := context.Background()
	const refresh = "zor_refresh_0123456789abcdef"
	stub := &countingMeStub{}
	stub.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		stub.calls.Add(1)
		token, _ := strings.CutPrefix(r.Header.Get("Authorization"), "Bearer ")
		w.Header().Set("Content-Type", "application/json")
		if strings.HasPrefix(token, "zor_") {
			// The backend never authenticates a refresh token on /v1
			// (zetic/public/auth.py rejects everything outside ztp_/zoa_).
			w.WriteHeader(http.StatusUnauthorized)
			_, _ = io.WriteString(w, `{"type":"error","error":{"type":"authentication_error","message":"Unauthorized"}}`)
			return
		}
		_, _ = io.WriteString(w, meBody("ok"))
	}))
	t.Cleanup(stub.Close)

	v := newTestMeVerifier(stub.URL, newFakeClock())
	for i := int64(1); i <= 2; i++ {
		_, err := v.Verify(ctx, refresh, nil)
		require.Error(t, err)
		assert.ErrorIs(t, err, auth.ErrInvalidToken, "a refresh token is a bad credential (401), not an outage (500)")
		assert.NotContains(t, err.Error(), refresh, "verifier errors must never carry the token")
		assert.Equal(t, i, stub.calls.Load(), "refresh-token rejections must not be cached")
	}
}

// TestResourceConfigEnforcesAudienceThroughStack proves the wiring end to
// end: Config.Resource ALONE (ValidateTokens deliberately false) must
// activate the verifier — a resource-declaring operator asked for audience
// enforcement, and passthrough can never provide it. A token bound elsewhere
// dies at the door with the challenge and reaches no tool; a matching-aud
// token and a PAT both run tools.
func TestResourceConfigEnforcesAudienceThroughStack(t *testing.T) {
	const (
		canonical = "https://mcp.zetic.ai"
		matched   = "zoa_bound_here_1732050808"
		wrong     = "zoa_bound_elsewhere_2236067977"
		pat       = "ztp_plain_pat_1414213562"
	)
	stub := &countingMeStub{}
	stub.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		stub.calls.Add(1)
		token, _ := strings.CutPrefix(r.Header.Get("Authorization"), "Bearer ")
		w.Header().Set("Content-Type", "application/json")
		switch token {
		case matched:
			_, _ = io.WriteString(w, meOAuthBody("bound", strPtr(canonical)))
		case wrong:
			_, _ = io.WriteString(w, meOAuthBody("stray", strPtr("https://other.example")))
		case pat:
			_, _ = io.WriteString(w, meBody("patty"))
		default:
			w.WriteHeader(http.StatusUnauthorized)
			_, _ = io.WriteString(w, `{"type":"error","error":{"type":"authentication_error","message":"Unauthorized"}}`)
		}
	}))
	t.Cleanup(stub.Close)

	_, ts := newTestServer(t, stub.URL, func(c *Config) { c.Resource = canonical })

	// The mismatched token is refused at the door: SDK 401 whose challenge
	// now carries the RFC 9728 discovery pointer (a resource identity is
	// configured), one upstream check, and neither the resource URLs nor the
	// token in the body.
	resp := postMCP(t, ts.URL, wrong, "", strings.NewReader(initializeBody))
	assert.Equal(t, http.StatusUnauthorized, resp.StatusCode)
	assert.Equal(t, `Bearer resource_metadata="`+canonical+protectedResourceWellKnown+`"`,
		resp.Header.Get("WWW-Authenticate"))
	body, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	assert.NotContains(t, string(body), wrong, "the bearer must never appear in the 401 body")
	assert.NotContains(t, string(body), "other.example", "the token's aud must never appear in the 401 body")
	assert.NotContains(t, string(body), canonical, "the configured resource must never appear in the 401 body")
	assert.Equal(t, int64(1), stub.calls.Load(),
		"rejection happens at the door — the MCP handler and tools are never reached")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// A token bound to THIS resource runs tools.
	session := connectSession(t, ctx, ts.URL, matched)
	text, isErr, err := callWhoami(ctx, session)
	require.NoError(t, err)
	assert.False(t, isErr, "a matching-audience token must run tools: %s", text)
	assert.Contains(t, text, "bound@example.com")

	// A PAT (no aud) stays accepted on the HTTP transport: audience
	// enforcement narrows bound tokens, it does not exclude PATs.
	session = connectSession(t, ctx, ts.URL, pat)
	text, isErr, err = callWhoami(ctx, session)
	require.NoError(t, err)
	assert.False(t, isErr, "a PAT must keep working with a resource configured: %s", text)
	assert.Contains(t, text, "patty@example.com")
}

// TestCanonicalResource pins the startup grammar of the canonical resource
// URL: what an operator may configure, and the canonical form everything
// downstream (audience comparison, the RFC 9728 document) sees.
func TestCanonicalResource(t *testing.T) {
	valid := []struct {
		in, want string
	}{
		{"https://mcp.zetic.ai", "https://mcp.zetic.ai"},
		{"https://mcp.zetic.ai/", "https://mcp.zetic.ai"},
		{"https://MCP.Zetic.AI", "https://mcp.zetic.ai"},
		{"https://mcp.zetic.ai/mcp/", "https://mcp.zetic.ai/mcp"},
		{"  https://mcp.zetic.ai  ", "https://mcp.zetic.ai"},
		{"http://localhost:8321", "http://localhost:8321"},
		{"http://127.0.0.1:9090", "http://127.0.0.1:9090"},
		{"http://[::1]:8080", "http://[::1]:8080"},
	}
	for _, tc := range valid {
		t.Run("valid "+tc.in, func(t *testing.T) {
			got, err := CanonicalResource(tc.in)
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)
		})
	}

	invalid := []struct {
		name, in string
	}{
		{"empty", ""},
		{"whitespace only", "   "},
		{"no scheme", "mcp.zetic.ai"},
		{"wrong scheme", "ftp://mcp.zetic.ai"},
		{"http on a public host", "http://mcp.zetic.ai"},
		{"http on a private, non-loopback IP", "http://192.168.1.10:8080"},
		{"query component", "https://mcp.zetic.ai?tenant=1"},
		{"fragment component", "https://mcp.zetic.ai#frag"},
		{"userinfo", "https://user:pw@mcp.zetic.ai"},
		{"no host", "https://"},
		{"unparsable", "://bad"},
	}
	for _, tc := range invalid {
		t.Run("invalid "+tc.name, func(t *testing.T) {
			_, err := CanonicalResource(tc.in)
			require.Error(t, err)
		})
	}
}

func TestMeVerifierCachesPositiveResults(t *testing.T) {
	ctx := context.Background()
	stub := newCountingMeStub(t, map[string]string{"token-alice": "alice"})
	clk := newFakeClock()
	v := newTestMeVerifier(stub.URL, clk)

	// Second verification inside the TTL is served from cache.
	for i := 0; i < 3; i++ {
		info, err := v.Verify(ctx, "token-alice", nil)
		require.NoError(t, err)
		assert.Equal(t, []string{"read"}, info.Scopes, "cache hits carry the full TokenInfo")
	}
	assert.Equal(t, int64(1), stub.calls.Load(), "verifications inside the TTL must not re-hit /v1/me")

	// Just inside the TTL: still cached.
	clk.Advance(meCacheTTL - time.Second)
	_, err := v.Verify(ctx, "token-alice", nil)
	require.NoError(t, err)
	assert.Equal(t, int64(1), stub.calls.Load())

	// Past the TTL: revalidate upstream.
	clk.Advance(2 * time.Second)
	_, err = v.Verify(ctx, "token-alice", nil)
	require.NoError(t, err)
	assert.Equal(t, int64(2), stub.calls.Load(), "an expired cache entry must be revalidated")
}

func TestMeVerifierNeverCachesNegatives(t *testing.T) {
	ctx := context.Background()
	stub := newCountingMeStub(t, map[string]string{})
	v := newTestMeVerifier(stub.URL, newFakeClock())

	for i := int64(1); i <= 3; i++ {
		_, err := v.Verify(ctx, "token-bad", nil)
		require.Error(t, err)
		assert.ErrorIs(t, err, auth.ErrInvalidToken)
		assert.NotContains(t, err.Error(), "token-bad", "verifier errors must never carry the bearer")
		assert.Equal(t, i, stub.calls.Load(),
			"negative results must not be cached: a just-created token has to work next request")
	}
}

// TestMeVerifierUpstreamFailureIsNotInvalidToken: an API outage must not
// masquerade as a bad credential — the SDK turns non-ErrInvalidToken errors
// into a 500, telling the client to retry rather than discard its token.
func TestMeVerifierUpstreamFailureIsNotInvalidToken(t *testing.T) {
	ctx := context.Background()

	// Unexpected status (404: not retried by the API transport, unlike 5xx).
	stub := httptest.NewServer(http.HandlerFunc(http.NotFound))
	t.Cleanup(stub.Close)
	v := newTestMeVerifier(stub.URL, newFakeClock())
	_, err := v.Verify(ctx, "token-a", nil)
	require.Error(t, err)
	assert.NotErrorIs(t, err, auth.ErrInvalidToken)
	assert.NotContains(t, err.Error(), stub.Listener.Addr().String(),
		"a status-derived message must not name the backend either")

	// Transport failure (a refused dial; the OS wording varies, so assertions
	// anchor on Go's own "dial tcp addr:" marker). The SDK copies err.Error()
	// into the 500 body, so this error must be the static sentinel and must
	// not carry the *url.Error's host or dial detail.
	deadURL := deadHost(t)
	logs := &syncBuffer{}
	v = newTestMeVerifierLogging(deadURL, newFakeClock(),
		slog.New(slog.NewTextHandler(logs, &slog.HandlerOptions{Level: slog.LevelDebug})))
	_, err = v.Verify(ctx, "token-a", nil)
	require.Error(t, err)
	assert.NotErrorIs(t, err, auth.ErrInvalidToken)
	assert.ErrorIs(t, err, errValidationUnavailable)
	assert.Equal(t, "token validation unavailable", err.Error(),
		"transport-failure text is static: the SDK publishes it verbatim in the 500 body")
	deadAddr := strings.TrimPrefix(deadURL, "http://")
	assert.NotContains(t, err.Error(), deadAddr)

	// ...and the withheld detail is not merely dropped: an operator can still
	// see which host failed and why.
	captured := logs.String()
	assert.Contains(t, captured, deadAddr, "the failing backend address must reach the server log")
	assert.Contains(t, captured, dialFailureMarker(deadAddr), "the dial fault must reach the server log")
	assert.NotContains(t, captured, "token-a", "the bearer must never reach the server log")
}

// TestMeVerifierTransportFailureLeaksNothingThroughStack is the wire-level
// proof of the same contract: with --validate-tokens and the backend
// unreachable, any caller holding a bearer-shaped string gets a 500 whose body
// names neither the backend nor the network fault, while the server log keeps
// both.
func TestMeVerifierTransportFailureLeaksNothingThroughStack(t *testing.T) {
	const bearer = "super-secret-transport-bearer-1414213562"
	deadURL := deadHost(t)
	deadAddr := strings.TrimPrefix(deadURL, "http://")

	logs := &syncBuffer{}
	_, ts := newTestServer(t, deadURL, func(c *Config) {
		c.ValidateTokens = true
		c.Logger = slog.New(slog.NewTextHandler(logs, &slog.HandlerOptions{Level: slog.LevelDebug}))
	})

	resp := postMCP(t, ts.URL, bearer, "", strings.NewReader(initializeBody))
	require.Equal(t, http.StatusInternalServerError, resp.StatusCode,
		"an unreachable backend is not a bad credential: 500, not 401")
	raw, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	body := string(raw)

	assert.Contains(t, body, "token validation unavailable")
	assert.NotContains(t, body, deadAddr, "the backend address must never reach the response body")
	assert.NotContains(t, body, dialFailureMarker(deadAddr), "net-layer detail must never reach the response body")
	assert.NotContains(t, body, "dial tcp", "net-layer detail must never reach the response body")
	assert.NotContains(t, body, bearer, "the bearer must never reach the response body")

	captured := logs.String()
	assert.Contains(t, captured, deadAddr, "the operator must still learn which backend failed")
	assert.Contains(t, captured, dialFailureMarker(deadAddr), "the operator must still learn why it failed")
	assert.NotContains(t, captured, bearer, "the bearer must never reach the server log")
}

// TestMeVerifierCacheBounded pins the size bound under a token spray: the
// cache must never exceed meCacheMaxEntries live entries.
func TestMeVerifierCacheBounded(t *testing.T) {
	ctx := context.Background()
	// Accept every token so each distinct bearer becomes a positive entry.
	stub := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, meBody("spray"))
	}))
	t.Cleanup(stub.Close)
	v := newTestMeVerifier(stub.URL, newFakeClock())

	for i := 0; i < meCacheMaxEntries+64; i++ {
		_, err := v.Verify(ctx, fmt.Sprintf("token-%04d", i), nil)
		require.NoError(t, err)

		v.mu.Lock()
		size := len(v.cache)
		v.mu.Unlock()
		require.LessOrEqual(t, size, meCacheMaxEntries,
			"cache must stay bounded while a token spray is in progress")
	}
}

// TestMeVerifierConcurrent exercises the cache under -race: many goroutines,
// overlapping tokens, all must verify successfully with the bound held.
func TestMeVerifierConcurrent(t *testing.T) {
	ctx := context.Background()
	stub := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, meBody("conc"))
	}))
	t.Cleanup(stub.Close)
	clk := newFakeClock()
	v := newTestMeVerifier(stub.URL, clk)

	var wg sync.WaitGroup
	for g := 0; g < 8; g++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := 0; i < 50; i++ {
				token := fmt.Sprintf("token-%d", i%10)
				info, err := v.Verify(ctx, token, nil)
				assert.NoError(t, err)
				assert.NotNil(t, info)
				if i%7 == 0 {
					clk.Advance(10 * time.Second)
				}
			}
		}()
	}
	wg.Wait()

	v.mu.Lock()
	size := len(v.cache)
	v.mu.Unlock()
	assert.LessOrEqual(t, size, meCacheMaxEntries)
}

// TestBearerNeverInLogs is THE credential-hygiene test: with debug-level
// logging capturing everything the server emits, a full mix of traffic —
// successful tool calls, token-validation rejections, and rate-limited
// requests — must leave zero bearer bytes in the logs.
func TestBearerNeverInLogs(t *testing.T) {
	const (
		good = "super-secret-good-bearer-1618033988"
		bad  = "super-secret-bad-bearer-2718281828"
	)
	stub := newMeStub(t, map[string]string{good: "ana"})

	logs := &syncBuffer{}
	logger := slog.New(slog.NewTextHandler(logs, &slog.HandlerOptions{Level: slog.LevelDebug}))
	srv, ts := newTestServer(t, stub.URL, func(c *Config) {
		c.ValidateTokens = true
		c.Logger = logger
	})

	// Successful tool call with the good bearer.
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	session := connectSession(t, ctx, ts.URL, good)
	text, isErr, err := callWhoami(ctx, session)
	require.NoError(t, err)
	assert.False(t, isErr, "tool call failed: %s", text)

	// Rejected bearer (401 via MeVerifier).
	resp := postMCP(t, ts.URL, bad, "", strings.NewReader(initializeBody))
	assert.Equal(t, http.StatusUnauthorized, resp.StatusCode)

	// Rate-limited requests (429): freeze the limiter clock so the bucket
	// cannot refill, then overrun the burst.
	srv.limiter.mu.Lock()
	srv.limiter.now = newFakeClock().Now
	srv.limiter.mu.Unlock()
	saw429 := false
	for i := 0; i < rateLimitBurst+2; i++ {
		resp := postMCP(t, ts.URL, good, "", strings.NewReader(initializeBody))
		if resp.StatusCode == http.StatusTooManyRequests {
			saw429 = true
		}
	}
	require.True(t, saw429, "burst overrun must produce a 429 for the log-hygiene sweep")

	// Transport failure: the one path that deliberately logs the underlying
	// error. It must log the backend fault and still no bearer bytes.
	deadURL := deadHost(t)
	_, err = newTestMeVerifierLogging(deadURL, newFakeClock(), logger).
		Verify(ctx, good, nil)
	require.Error(t, err)

	// Audience mismatch: the other path that deliberately logs detail (the
	// two resource URLs). It must log the mismatch and still no bearer bytes.
	const bound = "super-secret-bound-bearer-3141592653"
	audStub := staticBodyStub(t, meOAuthBody("stray", strPtr("https://elsewhere.example")))
	_, err = newTestMeVerifierResource(audStub.URL, "https://mcp.zetic.ai", newFakeClock(), logger).
		Verify(ctx, bound, nil)
	require.ErrorIs(t, err, auth.ErrInvalidToken)

	captured := logs.String()
	assert.Contains(t, captured, dialFailureMarker(strings.TrimPrefix(deadURL, "http://")),
		"the transport-failure detail must be logged, not silently dropped")
	assert.Contains(t, captured, "elsewhere.example",
		"the audience-mismatch detail must be logged, not silently dropped")
	assert.NotContains(t, captured, good, "bearer token leaked into server logs")
	assert.NotContains(t, captured, bad, "rejected bearer leaked into server logs")
	assert.NotContains(t, captured, bound, "audience-mismatched bearer leaked into server logs")
}
