// Command gendocs regenerates the Markdown CLI reference in docs/reference
// from the live cobra command tree. Run it via `make docs`; CI enforces
// freshness via `make docs-check`.
package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/zetic-ai/melange-cli/internal/cmd/root"
	"github.com/zetic-ai/melange-cli/internal/cmdutil"
	"github.com/zetic-ai/melange-cli/internal/config"
	"github.com/zetic-ai/melange-cli/internal/iostreams"
)

func main() {
	outDir := "docs/reference"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}
	if err := run(outDir); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	f := &cmdutil.Factory{
		IOStreams:  iostreams.System(),
		Executable: "melange",
		Config:     func() (*config.Config, error) { return config.Load() },
	}
	cmd := root.NewCmdRoot(f)

	// Deterministic output: no "Auto generated by spf13/cobra on <date>"
	// footers, so `make docs-check` stays byte-stable across runs.
	disableAutoGenTag(cmd)

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := doc.GenMarkdownTree(cmd, outDir); err != nil {
		return err
	}
	return normalizeMarkdownEndings(outDir)
}

func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

func normalizeMarkdownEndings(root string) error {
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		normalized := append(bytes.TrimRight(raw, "\r\n"), '\n')
		if bytes.Equal(raw, normalized) {
			return nil
		}
		return os.WriteFile(path, normalized, 0o644)
	})
}
